### PR TITLE
Adding code and folder for cleaning step

### PR DESCRIPTION
**Pull request by nicolassaw**
Additions:
-Folder for cleaning-related code and resources
-Code that cleans the data, for example, by simplifying the charge description -A database from the University of Michigan of what general types of charges each charge may be

### CODE REVIEW

**Comment by nicolassaw** [comment]
Specifically, this cleaner folder should be in the src folder.

**Review by normaljosh — APPROVED** [review]
Thanks for putting it in the same project! Hoping this got to the point where it's in the shape that the frontend expects it, won't have time to validate that but approving that it's in the right place

**Comment by nicolassaw** [comment]
Thanks! I will open an another ticket to see what that format looks like and to conform the final result to match.

**Comment by nicolassaw** [comment]
On second thought, I think that this folder is best supposed to be inside of the src folder, since it follows the scraper and parser step. @normaljosh What's the best way to move a folder within a subfolder? A new pull request where I delete and reupload?

**Comment by normaljosh** [comment]
@nicolassaw I think so! Once it's merged and closed looks like it can't be re-opened

**Pull request merged**
